In [2]:
import pandas as pd

In [ ]:
orders = '../databases/orders.csv'
order_items = '../databases/order_items.csv'
users = '../databases/users.csv'

Read csv_files

In [4]:
orders_df = pd.read_csv(orders)
order_items_df = pd.read_csv(order_items)

Convert created_at in orders table to datetime

In [5]:
orders_df["created_at"] = pd.to_datetime(
    orders_df["created_at"],
    format="ISO8601"
)

In [6]:
orders_df

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,8,8,Cancelled,F,2023-07-22 08:23:24+00:00,NaN,NaN,NaN,1
1,29,29,Cancelled,F,2026-02-10 06:15:05+00:00,NaN,NaN,NaN,1
2,60,59,Cancelled,F,2025-06-07 05:45:33+00:00,NaN,NaN,NaN,1
3,65,62,Cancelled,F,2026-05-18 07:09:09+00:00,NaN,NaN,NaN,1
4,68,63,Cancelled,F,2023-11-25 02:08:33+00:00,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...
125417,125394,99983,Shipped,M,2025-12-16 06:39:56+00:00,NaN,2025-12-17 12:21:56+00:00,NaN,1
125418,125402,99987,Shipped,M,2026-03-22 15:35:15+00:00,NaN,2026-03-24 05:13:15+00:00,NaN,1
125419,125417,99997,Shipped,M,2022-05-15 22:42:57+00:00,NaN,2022-05-15 23:08:57+00:00,NaN,1
125420,125418,99997,Shipped,M,2025-02-17 08:47:30+00:00,NaN,2025-02-18 17:29:30+00:00,NaN,1
125421,125419,99998,Shipped,M,2024-02-16 08:43:15+00:00,NaN,2024-02-17 03:31:15+00:00,NaN,3

Join orders_df and order_items_df

In [7]:
merged_df = orders_df.merge(
    order_items_df,
    on="order_id",
    how="inner"
)

Where condition at status column in orders table

In [8]:
filtered_df = merged_df[
    ~merged_df["status_x"].isin(["Cancelled", "Returned"])
]

Date trunc created_at column in orders table to month

In [9]:
filtered_df["order_month"] = (
    filtered_df["created_at_x"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

C:\Users\User\AppData\Local\Temp\ipykernel_3536\679013642.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .dt.to_period("M")
C:\Users\User\AppData\Local\Temp\ipykernel_3536\679013642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["order_month"] = (

In [10]:
filtered_df

,order_id,user_id_x,status_x,gender,created_at_x,returned_at_x,shipped_at_x,delivered_at_x,num_of_item,id,user_id_y,product_id,inventory_item_id,status_y,created_at_y,shipped_at_y,delivered_at_y,returned_at_y,sale_price,order_month
13561,3,5,Complete,F,2026-03-14 17:22:22+00:00,NaN,2026-03-16 20:06:22+00:00,2026-03-21 02:51:22+00:00,1,5,5,7842,16,Complete,2026-03-14 16:02:46+00:00,2026-03-16 20:06:22+00:00,2026-03-21 02:51:22+00:00,NaN,258.000000,2026-03-01
13562,19,15,Complete,F,2019-09-29 15:57:33+00:00,NaN,2019-10-01 02:36:33+00:00,2019-10-04 17:25:33+00:00,1,32,15,7069,87,Complete,2019-09-29 13:56:42+00:00,2019-10-01 02:36:33+00:00,2019-10-04 17:25:33+00:00,NaN,9.900000,2019-09-01
13563,22,20,Complete,F,2022-12-25 08:52:42+00:00,NaN,2022-12-25 21:12:42+00:00,2022-12-29 02:47:42+00:00,1,35,20,5500,94,Complete,2022-12-25 05:47:20+00:00,2022-12-25 21:12:42+00:00,2022-12-29 02:47:42+00:00,NaN,78.000000,2022-12-01
13564,23,20,Complete,F,2025-02-08 20:09:35+00:00,NaN,2025-02-10 04:46:35+00:00,2025-02-10 19:16:35+00:00,1,36,20,12872,96,Complete,2025-02-08 19:33:40+00:00,2025-02-10 04:46:35+00:00,2025-02-10 19:16:35+00:00,NaN,24.990000,2025-02-01
13565,30,29,Complete,F,2026-01-06 01:36:36+00:00,NaN,2026-01-08 16:23:36+00:00,2026-01-11 21:30:36+00:00,1,48,29,11366,126,Complete,2026-01-06 00:43:58+00:00,2026-01-08 16:23:36+00:00,2026-01-11 21:30:36+00:00,NaN,16.500000,2026-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181514,125417,99997,Shipped,M,2022-05-15 22:42:57+00:00,NaN,2022-05-15 23:08:57+00:00,NaN,1,181512,99997,18818,489645,Shipped,2022-05-15 21:25:32+00:00,2022-05-15 23:08:57+00:00,NaN,NaN,45.990002,2022-05-01
181515,125418,99997,Shipped,M,2025-02-17 08:47:30+00:00,NaN,2025-02-18 17:29:30+00:00,NaN,1,181513,99997,24870,489649,Shipped,2025-02-17 08:14:15+00:00,2025-02-18 17:29:30+00:00,NaN,NaN,20.950001,2025-02-01
181516,125419,99998,Shipped,M,2024-02-16 08:43:15+00:00,NaN,2024-02-17 03:31:15+00:00,NaN,3,181515,99998,28912,489654,Shipped,2024-02-19 07:35:34+00:00,2024-02-17 03:31:15+00:00,NaN,NaN,14.950000,2024-02-01
181517,125419,99998,Shipped,M,2024-02-16 08:43:15+00:00,NaN,2024-02-17 03:31:15+00:00,NaN,3,181514,99998,20636,489652,Shipped,2024-02-20 07:12:43+00:00,2024-02-17 03:31:15+00:00,NaN,NaN,29.990000,2024-02-01
181518,125419,99998,Shipped,M,2024-02-16 08:43:15+00:00,NaN,2024-02-17 03:31:15+00:00,NaN,3,181516,99998,28880,489656,Shipped,2024-02-18 06:11:20+00:00,2024-02-17 03:31:15+00:00,NaN,NaN,104.949997,2024-02-01

Group joined tables by order_month and order_id column and sum the sale_price

In [11]:
monthly_orders = (
    filtered_df
    .groupby(["order_month", "order_id"], as_index=False)
    ["sale_price"]
    .sum()
)

In [12]:
monthly_orders

      order_month  order_id  sale_price
0      2019-01-01      7852   39.990002
1      2019-01-01     33411   35.000000
2      2019-01-01     35366   28.500000
3      2019-01-01     75401  328.100010
4      2019-01-01     96067   65.839996
...           ...       ...         ...
94020  2026-05-01    125326    9.950000
94021  2026-05-01    125335  255.000000
94022  2026-05-01    125350   69.500000
94023  2026-05-01    125355  197.500000
94024  2026-05-01    125358   74.990002

[94025 rows x 3 columns]

In [13]:
monthly_orders = monthly_orders.rename(columns={
    "sale_price": "order_revenue"
})

In [14]:
monthly_orders

      order_month  order_id  order_revenue
0      2019-01-01      7852      39.990002
1      2019-01-01     33411      35.000000
2      2019-01-01     35366      28.500000
3      2019-01-01     75401     328.100010
4      2019-01-01     96067      65.839996
...           ...       ...            ...
94020  2026-05-01    125326       9.950000
94021  2026-05-01    125335     255.000000
94022  2026-05-01    125350      69.500000
94023  2026-05-01    125355     197.500000
94024  2026-05-01    125358      74.990002

[94025 rows x 3 columns]

In [15]:
monthly_orders["order_revenue"].sum()

np.float64(8076892.547762394)

In [17]:
monthly_summary_df = (
monthly_orders
.groupby("order_month", as_index=False)
.agg(
    num_orders=("order_id", "count"),
    gmv=("order_revenue", "sum"),
    aov=("order_revenue", "mean")))
monthly_summary_df

   order_month  num_orders            gmv         aov
0   2019-01-01           6     684.930008  114.155001
1   2019-02-01          15     700.220001   46.681333
2   2019-03-01          25    2346.889993   93.875600
3   2019-04-01          55    5261.999995   95.672727
4   2019-05-01          64    5122.149998   80.033594
..         ...         ...            ...         ...
84  2026-01-01        3193  275348.290260   86.234980
85  2026-02-01        3086  267522.030306   86.688928
86  2026-03-01        3871  330604.870267   85.405546
87  2026-04-01        4414  385413.940416   87.316253
88  2026-05-01        7056  609184.230527   86.335634

[89 rows x 4 columns]

GMV Should not be negative

In [18]:
monthly_summary_df["gmv"].min()

np.float64(684.9300079345703)